const MAX_BYTES=5*1024*1024;
const ALLOWED=new Set(['image/jpeg','image/png','image/webp']);
const demoMeals=[
 {name:'Chicken, rice & broccoli',items:[{name:'Chicken breast, grilled',grams:150,calories:248,protein:46.5,carbs:0,fat:5.4,confidence:.62},{name:'Brown rice, cooked',grams:195,calories:216,protein:5,carbs:45,fat:1.8,confidence:.55},{name:'Broccoli, steamed',grams:150,calories:55,protein:3.7,carbs:11,fat:.6,confidence:.58}]},
 {name:'Breakfast plate',items:[{name:'Egg, large',grams:100,calories:144,protein:12.6,carbs:.8,fat:9.6,confidence:.57},{name:'Whole wheat bread',grams:56,calories:162,protein:8,carbs:28,fat:2.2,confidence:.52},{name:'Avocado, half',grams:75,calories:120,protein:1.5,carbs:6.4,fat:11,confidence:.5}]},
 {name:'Yogurt, fruit & almonds',items:[{name:'Greek yogurt, plain',grams:200,calories:146,protein:16.5,carbs:8,fat:3.9,confidence:.6},{name:'Strawberries, cup',grams:150,calories:49,protein:1,carbs:11.7,fat:.5,confidence:.54},{name:'Almonds, 28g',grams:28,calories:164,protein:6,carbs:6,fat:14,confidence:.48}]}
];
const response=(status,body)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
function parseDataUrl(value){const m=/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/.exec(value||'');if(!m||!ALLOWED.has(m[1]))return null;return{mime:m[1],base64:m[2],bytes:Math.floor(m[2].length*3/4)}}
function normalize(raw){if(!raw||!Array.isArray(raw.items)||!raw.items.length)throw new Error('No food items detected');const items=raw.items.slice(0,8).map((x,i)=>({id:`photo-${Date.now()}-${i}`,name:String(x.name||'Unknown food').slice(0,80),grams:Math.max(1,Math.min(2000,Number(x.grams)||100)),calories:Math.max(0,Number(x.calories)||0),protein:Math.max(0,Number(x.protein)||0),carbs:Math.max(0,Number(x.carbs)||0),fat:Math.max(0,Number(x.fat)||0),confidence:Math.max(0,Math.min(1,Number(x.confidence)||0))}));return{name:String(raw.name||'Photo meal').slice(0,80),items,overallConfidence:items.reduce((a,x)=>a+x.confidence,0)/items.length}}
async function providerEstimate(image){const prompt=`Estimate the visible foods and portions. Return JSON only: {"name":"meal name","items":[{"name":"food","grams":number,"calories":number,"protein":number,"carbs":number,"fat":number,"confidence":number 0..1}]}. Confidence must reflect both food identity and portion uncertainty. Do not claim certainty from one image.`;const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.CALAI_VISION_MODEL||'gpt-4o-mini',response_format:{type:'json_object'},temperature:0,messages:[{role:'user',content:[{type:'text',text:prompt},{type:'image_url',image_url:{url:`data:${image.mime};base64,${image.base64}`}}]}]})});if(!r.ok)throw new Error(`Vision provider returned ${r.status}`);const data=await r.json();return normalize(JSON.parse(data.choices?.[0]?.message?.content||'{}'))}
export default async req=>{if(req.method!=='POST')return response(405,{error:'Method not allowed'});try{const body=await req.json(),image=parseDataUrl(body.image);if(!image)return response(400,{error:'Use a JPEG, PNG, or WebP photo.'});if(image.bytes>MAX_BYTES)return response(413,{error:'Photo must be 5 MB or smaller.'});if(process.env.OPENAI_API_KEY){const estimate=await providerEstimate(image);return response(200,{...estimate,mode:'provider',disclaimer:'AI estimates can be wrong. Check every item and portion before logging.'})}const seed=(body.fileName||'meal').split('').reduce((a,c)=>a+c.charCodeAt(0),0);const estimate=normalize(demoMeals[seed%demoMeals.length]);return response(200,{...estimate,mode:'demo',disclaimer:'Demo estimate—not image analysis. Check every item and portion before logging.'})}catch(e){console.error('meal estimate failed',e.message);return response(502,{error:'We could not estimate this meal. Try a clearer photo or log it by search.'})}}
export const config={path:'/api/estimate-meal'};
